# Generated by Django 4.2.7 on 2026-02-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcustomer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='webcustomer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='webcustomer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='webcustomer',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='webcustomer',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcustomer',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing'), ('both', 'Both')], default='shipping', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='orders.webcustomer')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
