# Generated by Django 6.0.2 on 2026-02-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_webcustomer_address_remove_webcustomer_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcustomer',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='webcustomer',
            name='newsletter_subscribed',
        ),
        migrations.AddField(
            model_name='webcustomer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webcustomer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='webcustomer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='webcustomer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
