# Generated by Django 6.0.2 on 2026-02-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_webcustomer_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcustomer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
