# Generated by Django 6.0.2 on 2026-02-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_webcustomer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax rate at time of purchase', max_digits=5, null=True),
        ),
    ]
