# Generated by Django 4.2.7 on 2026-05-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_info',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
