# Generated by Django 6.0.2 on 2026-02-14 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='can_manage_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_manage_finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_manage_sellers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_view_all_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_view_own_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_switched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='original_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('inventory_manager', 'Inventory Manager'), ('order_manager', 'Order Manager'), ('support', 'Customer Support'), ('accountant', 'Accountant'), ('delivery_person', 'Delivery Person'), ('seller', 'Seller'), ('viewer', 'Viewer'), ('customer', 'Customer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('inventory_manager', 'Inventory Manager'), ('order_manager', 'Order Manager'), ('support', 'Customer Support'), ('accountant', 'Accountant'), ('delivery_person', 'Delivery Person'), ('seller', 'Seller'), ('viewer', 'Viewer'), ('customer', 'Customer')], default='viewer', max_length=20),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('manage_products', 'Manage Products'), ('manage_orders', 'Manage Orders'), ('manage_inventory', 'Manage Inventory'), ('manage_customers', 'Manage Customers'), ('manage_staff', 'Manage Staff'), ('manage_sellers', 'Manage Sellers'), ('view_reports', 'View Reports'), ('manage_settings', 'Manage Settings'), ('manage_finance', 'Manage Finance'), ('manage_delivery', 'Manage Delivery'), ('view_all_orders', 'View All Orders'), ('view_own_orders', 'View Own Orders')], max_length=50)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('can_grant', models.BooleanField(default=False)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
