# Generated by Django 6.0.2 on 2026-02-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_staffprofile_can_manage_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='tax_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
