# Generated by Django 6.0.2 on 2026-02-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_siteconfiguration_tax_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='currency_name',
            field=models.CharField(default='US Dollar', help_text='Full currency name', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='currency_short_form',
            field=models.CharField(default='USD', help_text='Short form like Tk, $, BDT', max_length=10),
        ),
    ]
