# Generated by Django 6.0.2 on 2026-02-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_siteconfiguration_currency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='auto_cancel_hours',
            field=models.IntegerField(default=48, help_text='Hours before cancelling unpaid orders'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='auto_cancel_unpaid_orders',
            field=models.BooleanField(default=False, help_text='Automatically cancel unpaid orders after X hours'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_database_backup',
            field=models.BooleanField(default=True, help_text='Allow database backup downloads'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='notification_email',
            field=models.EmailField(default='admin@techshop.com', help_text='Email address for notifications', max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='notify_low_stock',
            field=models.BooleanField(default=True, help_text='Notify admins when stock is low'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='notify_new_order',
            field=models.BooleanField(default=True, help_text='Notify admins when new order is placed'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='notify_new_review',
            field=models.BooleanField(default=True, help_text='Notify admins when new review is submitted'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='notify_order_status_change',
            field=models.BooleanField(default=True, help_text='Notify customers when order status changes'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='require_approval_for_reviews',
            field=models.BooleanField(default=True, help_text='Require admin approval before reviews are visible'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='reviews_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable product reviews'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_database_status',
            field=models.BooleanField(default=True, help_text='Display database connection status'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_system_health',
            field=models.BooleanField(default=True, help_text='Display system health metrics on dashboard'),
        ),
    ]
