# Generated by Django 6.0.2 on 2026-02-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_supplier_inventorymovement_purchaseorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='currency_symbol',
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='currency_short_form',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('BDT', 'BDT - Bangladeshi Taka'), ('INR', 'INR - Indian Rupee'), ('PKR', 'PKR - Pakistani Rupee'), ('CNY', 'CNY - Chinese Yuan'), ('JPY', 'JPY - Japanese Yen'), ('KRW', 'KRW - South Korean Won'), ('AUD', 'AUD - Australian Dollar'), ('CAD', 'CAD - Canadian Dollar'), ('CHF', 'CHF - Swiss Franc'), ('SGD', 'SGD - Singapore Dollar'), ('MYR', 'MYR - Malaysian Ringgit'), ('THB', 'THB - Thai Baht'), ('VND', 'VND - Vietnamese Dong'), ('PHP', 'PHP - Philippine Peso'), ('IDR', 'IDR - Indonesian Rupiah'), ('AED', 'AED - UAE Dirham'), ('SAR', 'SAR - Saudi Riyal'), ('NZD', 'NZD - New Zealand Dollar'), ('SEK', 'SEK - Swedish Krona'), ('NOK', 'NOK - Norwegian Krone'), ('DKK', 'DKK - Danish Krone'), ('MXN', 'MXN - Mexican Peso'), ('BRL', 'BRL - Brazilian Real'), ('RUB', 'RUB - Russian Ruble'), ('ZAR', 'ZAR - South African Rand'), ('EGP', 'EGP - Egyptian Pound'), ('NGN', 'NGN - Nigerian Naira'), ('KES', 'KES - Kenyan Shilling')], default='USD', help_text='Short form like USD, EUR, BDT', max_length=10),
        ),
    ]
