# Generated by Django 6.0.2 on 2026-02-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_attributevalue_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_label',
            field=models.CharField(blank=True, help_text='e.g. Summer Sale, Flash Deal', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
