# Generated by Django 6.0.2 on 2026-02-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_exempt',
            field=models.BooleanField(default=False, help_text='Mark this product as tax-exempt'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product-specific tax rate. Leave empty to use global rate.', max_digits=5, null=True),
        ),
    ]
